### ISSUE TITLE
`--editor` option does not work in Windows

### ISSUE THREAD

**Issue by awood** [awood/hawkins#3]
On windows, at least, the post command doesn't accept the `-e` or `--editor` options, however, or at least I can't get it to work.

    jekyll 3.1.3 | Error: Whoops, we can't understand your command.
    jekyll 3.1.3 | Error: invalid option: -e
    jekyll 3.1.3 | Error: Run your command again with the --help switch to see available options.

--help isn't very...helpful.

From https://talk.jekyllrb.com/t/a-tool-for-automatic-browser-refreshes/2150#post_3

**Comment by awood** [comment]
Appears to not be a Windows specific issue.  Looks like just a bug on my part. :scream:

**Comment by cori** [comment]
As noted in the talk discussion, 2.0.2 fixes `-e` but not `--editor`. For my purposes this is sufficient, but if `--editor` should work then this might need to be reopened.

**Comment by awood** [comment]
Strange. `--editor` is working for me.  I wonder if this is actually a Windows issue with the double hyphen options not being recognized.  Does `jekyll post --help` work?

Also could you post the entire command you're running with `--editor` and the subsequent output?

Here's what I get (and gedit opens the appropriate file)
```
% jekyll post --editor gedit Hello
Configuration file: /home/awood/devel/website/_config.yml
Wrote /home/awood/devel/website/_posts/2016-05-16-hello.md 
```
